site_name: Documentation Sirocco

nav:
- Accueil : index.md
- Demo : doc_exemple.md
- SIDGFC : 
  - SIDGFC : sidgfc/sidgfc.md
  - Indicateurs : sidgfc/sidgfc_indicateurs.md

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: green 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      separator: "_"
      title: "Table of Contents"